Convert Scoutgame cron to worker env (#4589)
* set env id

* add server

* add start command for cron

* fix staging conf

* fix config

* try sqs

* try again

* add tier type

* fixz type

* fix again

* set tier in production

* rename yml file

* fix

* try copying cron to zip

* ..

* try again with cron

* change to every 5 minutes

* try new url

* uninstall node cron

* try binding to all ports

* change get to post handler

* change to 5 min

diff --git a/.github/actions/deploy_staging/action.yml b/.github/actions/deploy_staging/action.yml
--- a/.github/actions/deploy_staging/action.yml
+++ b/.github/actions/deploy_staging/action.yml
@@ -33,6 +33,12 @@ runs:
       with:
         app_name: ${{ inputs.app_name }}
 
+    - name: Setup cron config
+      shell: bash
+      # Note: "2>/dev/null || :" is a bash idiom that means "if the previous command fails, do nothing"
+      run: |
+        cp apps/${{ inputs.app_name }}/cron.yml cron.yaml 2>/dev/null || :
+
     - name: Replace env_var with staging settings
       shell: bash
       run: |
