Update precommit script

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,3 +2,18 @@
 . "$(dirname "$0")/_/husky.sh"
 
 npx lint-staged
+
+# List of files to check. These should already be in gitignore, but this provides an additional layer of protection.
+files_to_check=(".env.production" ".env.staging")
+
+# Loop over each file in the list and check for the forbidden string
+for file_to_check in "${files_to_check[@]}"; do
+  # Check if the file is staged for commit
+  if git diff --cached --name-only | grep -q "^$file_to_check$"; then
+    if grep -q "env.blocked" "$file_to_check"; then
+      echo "Error: 'env.blocked' found in staged file: $file_to_check"
+      echo "Please remove it and try again."
+      exit 1
+    fi
+  fi
+done
